#Fill here the Google Maps API keys for your application
#In this sample:
#For development and test, we have only one possible host (localhost:3000), so there is only a single key associated with the mode.
#In production, the app can be accessed through 2 different hosts: thepochisuperstarmegashow.com and exmaple.com. There then needs a 2-key hash. If you deployed to one host, only the API key would be needed (as in development and test).

development:
 ABQIAAAAbXvwir-2Phm0wHRmLTgGvxRi_j0U6kJrkFvY4-OX2XYmEAa76BSopFyEW1CEgyDylUb0eRg-5T_bIA

test:
 ABQIAAAAbXvwir-2Phm0wHRmLTgGvxQ04JgaWcVVK8KXWqi4dQuzqSkGdxRm_zhkU8-uD7j8bJBA8rZtv7PLDQ

production:
 inscryb.com:ABQIAAAAbXvwir-2Phm0wHRmLTgGvxQ04JgaWcVVK8KXWqi4dQuzqSkGdxRm_zhkU8-uD7j8bJBA8rZtv7PLDQ
